version: '3.8'

volumes:
  db_data:
  images_users:
  images_gallery:

services:
  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: storage
      MYSQL_DATABASE: storage
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 33006:3306

  storage:
    container_name: storage_mysql
    build: 
      context: ./micro_services/storage
      dockerfile: dev.Dockerfile
    depends_on:
      - db
    volumes:
      - ./micro_services/storage/src:/app/src
    ports:
      - 5555:5555
    environment:
      - PORT=6000

  gateway:
    container_name: gateway
    build:
      context: ./micro_services/gateway
      dockerfile: dev.Dockerfile
    volumes:
      - images_users:/app/public/images/users
      - images_gallery:/app/public/images/gallery
      - ./micro_services/gateway/src:/app/src
      - ./micro_services/gateway/public:/app/public
    depends_on:
      - storage
    environment:
      - PORT=6000
      - STORAGE_URL=http://storage:6000
    ports:
      - 3000:6000